### ISSUE TITLE
Організація контенту

### ISSUE THREAD

**Issue by IcedNecro** [KPI-FICT-IP32/KPI-FICT-IP32.github.io#1]
Копнув трохи доки і поняв що треба якось міняти організацію колекції. Автообновляючийся зміст буде фуричити, от тільки він розрізняє колекції тільки в корені проекта. Тобто якщо в папці ```_lectures``` ти будеш створювати підпапки під кожен предмет, то всі файли всеодно будуть показуватися в колекції ```_lectures```. Щоб розбити лекції по предметам в змістові, треба або під кожен предмет створювати колекцію, або в YAML ручками прописувати кожну нову лекцію по схожому принципу https://jekyllrb.com/docs/collections/#accessing-collection-attributes

**Comment by anxolerd** [comment]
По колекції під кожен предмет -- це ок. Тільки тре, щоб вони шукалися не у кореневому каталозі (щоб не засирати корінь проекту).

**Comment by IcedNecro** [comment]
треба глянути чи є можливість робить колекції не в корені проекту, а то я такої можливості поки не бачив

**Comment by anxolerd** [comment]
@IcedNecro: я не дуже уважно читав доку, але може є сенс спробувати pages замість collections: http://jekyllrb.com/docs/pages/
