### ISSUE TITLE
Документація

### ISSUE THREAD

**Issue by anxolerd** [KPI-FICT-IP32/KPI-FICT-IP32.github.io#20]
## Мета

Полегшити локальне розгортання проекту.

## Зробити

- [ ] Написати документацію по локальному розгортанню проекту.

## Примітка
Врахувати, що не усі використовують linux. Є й ті, хто користуються Windows та OSX.

**Comment by anxolerd** [comment]
ping @ValkoVolodya @IcedNecro: зможете зробити? І наскільки ОК тема?

**Comment by IcedNecro** [comment]
Мені здається це зайве. Установить ruby i jekyll не настільки складно, щоб робить контейнерізацію

**Comment by anxolerd** [comment]
@IcedNecro , OK, тоді залишаю тільки документування розгортання проекту локально.
