### ISSUE TITLE
Навігація між лекціями

### ISSUE THREAD

**Issue by anxolerd** [KPI-FICT-IP32/KPI-FICT-IP32.github.io#9]
## Мета
Покращити навігацію у блозі. Зробити блог більш зручним для читача

## Проблема
Наразі не дуже зручно переходити між лекціями однієї дисципліни. Зокрема, щоб перейти до 4 лекції після прочитання третьої, необхідно 
1. Повернутися на головну сторінку
2. Перейти до четвертої лекції

## Зробити
Додати до сторінки дописів посилання на попередній/наступний допис. В ідеалі -- на попередній/наступний допис у тій же категорії.

- [ ] Додати посилання на наступний та попередній дописи узагалі
- [ ] Перевірити, чи можливо зробити переходи лише між дописами у категорії
- [ ] Якщо переходи у категорії можливі -- зробити так, щоб посилання працювали у межах категорії

## Примітка
1. Можливо стане у нагоді [цей приклад](https://github.com/anxolerd/anxolerd.github.io/blob/master/_layouts/post.html#L23-L43) та [документація](http://jekyllrb.com/docs/variables/#page-variables)
2. Робити виключно у форку або окремій гілці та не зливати у `master` без проходження рев'ю.

**Comment by ValkoVolodya** [comment]
Я спробував зробити навігацію між постами, а саме: попередній та наступний, а також список з трьох схожих(не впевнений, чи це доцільно). 
Не знайшов поки як шукати наступний та попередній саме в категорії, але, думаю, це можливо, якщо якось його перевірити на приналежність.

**Comment by ValkoVolodya** [comment]
Потрібні також мінімальні описи стилів кнопок, а то посилання виглядають непрезентабельно.
